---
# tasks file for install
- name: Install httpd
  yum:
    name: httpd-{{ httpd_version}}
    state: present
- name: Start_httpd
  systemd:
    name: httpd
    state: started
- name: Enable_httpd_service
  systemd:
    name: httpd
    state: started
